config/routes.rb
Zui::Application.routes.draw do

  resources :translations

  get "comments/create"

  get "comments/update"

  get "comments/destroy"

  get "comments/new"

  get "comments/edit"

  get "comments/index"

  resources :projects do
    resources :fragments do

      get "translation_mode"
      
      resources :comments do
        get "reply"
      end
    end
  end
    

  devise_for :users

  match "users" => "user#index"

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_taggable
  belongs_to :fragment, :counter_cache => true
  belongs_to :user

  validates_presence_of :fragment, :user

  has_ancestry
end

app/controllers/comments_controller.rb
#encoding: utf-8
class CommentsController < ApplicationController
  def create
    @fragment= Fragment.find(params[:fragment_id])
    @comment = @fragment.comments.build(params[:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        @comments = @fragment.comments 
        format.js { flash[:notice] = "Kommentar erstellt."
                    render "index" }
        format.html { redirect_to [@fragment.project, @fragment], notice: 'Comment was successfully created.' }
      else
        #format.html { render action: "new" }
        #puts @fragment.errors
        #format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @fragment = Fragment.find(params[:fragment_id])
    @comments = @fragment.comments 
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.js { flash[:notice] = "Kommentar gespeichert"
                    render "index"}
      end
    end
  end

  def reply
    @parent = Comment.find(params[:comment_id])
    @fragment = @parent.fragment
    @project = @fragment.project
    @comment = Comment.new
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @fragment = Fragment.find(params[:fragment_id])
    @comments = @fragment.comments 
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js { flash[:notice] = "Kommentar gelöscht"
                  render "index" }
    end
  end

  def new
  end

  def edit
    @comment = Comment.find(params[:id])
    @fragment = @comment.fragment
    @project = @fragment.project
    respond_to do |format|
      format.js
    end
  end

  def index
    @comments = Fragment.find(params[:fragment_id]).comments
    respond_to do |format|
      format.js
    end 
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments) 
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested")
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_id_<%= comment.id %>">
  <div class="comment_head">
    <div class="comment_actions">
      <% if can? :edit, comment %>
        <%= link_to "Bearbeiten", edit_project_fragment_comment_path(comment.fragment.project, comment.fragment, comment), :remote => true %>
         | 
      <% end %>
      <%= link_to "Antworten", project_fragment_comment_reply_path(comment.fragment.project, comment.fragment, comment), :remote => true %>
      <% if can? :destroy, comment %>
        | 
        <%= link_to "x", [comment.fragment.project ,comment.fragment, comment], :method =>"delete", :remote => true, :confirm => "Wirklich löschen?" %>
      <% end %>
    </div>
    <%= image_tag comment.user.gravatar_link, :class => "avatar" %>
    <%= content_tag :span, comment.user.name, :class => "name" %>
    <%= l(comment.updated_at, :format => :short) %>
    <%= content_tag :div, comment.tag_list.map{|tag| content_tag :span, tag, :class => "label notice"}.join(" ").html_safe, :class => "tags" %>
  </div>
  <p><%= Kramdown::Document.new(comment.body).to_html.html_safe %></p>
</div>

app/views/comments/_form.html.erb
<div class="comment_form">
  <%= form_for [@project, @fragment, @comment], :html => {:class => "form-stacked"}, :remote => true do |f| %>
    <fieldset>
      <% if @parent %>
        <%= f.hidden_field :parent_id, :value => @parent.id %>
      <% end %>
      <% if @origin %>
        <%= "<input type='hidden' name='options[origin]' value='#{@origin}'>".html_safe%>
      <% end %>
      <div class="clearfix">
        <%= f.label :tag_list, t("comment.tags") %>
        <div class="input">
          <%= f.text_field :tag_list, :class => "xxlarge tag_list" %>
        </div>
      </div>
      <div class="clearfix">
        <%= f.label :body, t("comment.body")%>
        <div class="input">
          <%= f.text_area :body, :rows => 3, :class => "xxlarge"%>
        </div>
      </div>
      <div class="actions">
        <%= f.submit t("comment.submit"), :class => "btn primary"%>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$("#comments_text").html("<%= escape_javascript(render(@comments))%>")

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/edit.js.erb
$("#comment_id_<%=@comment.id%>").replaceWith("<%= escape_javascript(render "comments/form") %>");
$(".tag_list").tagsInput({height: "35px", width: "528px"});

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/index.js.erb
$("#comments_text").html("<%= escape_javascript(nested_comments(@comments.arrange))%>")
$("#flash-messages").html("<%= escape_javascript(render("devise/shared/flash-messages"))%>")

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/reply.js.erb
$(".comment_answer").remove();
$("#comment_id_<%=@parent.id%>").after("<div class='comment_answer nested'><%= escape_javascript(render "comments/form") %></div>");
$(".tag_list").tagsInput({height: "35px", width: "528px"});

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>