config/routes.rb
Zui::Application.routes.draw do

  resources :translations

  get "comments/create"

  get "comments/update"

  get "comments/destroy"

  get "comments/new"

  get "comments/edit"

  get "comments/index"

  resources :projects do
    resources :fragments do

      get "translation_mode"
      
      resources :comments do
        get "reply"
      end
    end
  end
    

  devise_for :users

  match "users" => "user#index"

  root :to => "home#index"

end

app/models/translation.rb
class Translation < ActiveRecord::Base
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
    @translation = Translation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/new
  # GET /translations/new.json
  def new
    @translation = Translation.new
    @translation.source_lang = params[:source_lang]

    respond_to do |format|
      format.js
      format.html # new.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/1/edit
  def edit
    @translation = Translation.find(params[:id])
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(params[:translation])

    respond_to do |format|
      if @translation.save
        format.js
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render json: @translation, status: :created, location: @translation }
      else
        format.html { render action: "new" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /translations/1
  # PUT /translations/1.json
  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= simple_form_for(@translation) do |f| %>
  <fieldset>
    <div class="clearfix">
      <%= f.label :source_lang%>
      <div class="input">
        <%= f.text_area :source_lang, :rows => 3%>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :target_lang%>
      <div class="input">
        <%= f.text_area :target_lang, :rows => 3%>
      </div>
    </div>
    <div class="actions">
      <%= f.submit t("translation.submit"), :class => "btn primary"%>
    </div>
  </fieldset>
<% end %>

app/views/translations/_modal_form.html.erb
<div id="modal-translation-form" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">x</a>
    <h3><%= t("translation.new") %></h3></div>
  <div class="modal-body"><%= render("form") %></div>
</div>

app/views/translations/create.js.erb
var el = $("#modal-translation-form");
$("#original-wrapper").load(window.location.toString() + " #original", undefined, function(){document.initializeTranslationMode();
el.modal("hide");
});

app/views/translations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span16">
      <h1>Übersetzung bearbeiten</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/translations/index.html.erb
<div class="container">
  <section id="index">
    <div class="row">
      <div class="span4 columns">
        <h3>Aktionen</h3>
        <p>
          <%= link_to 'Neue Übersetzung', new_translation_path, :class => "btn primary" %>
        </p>
      </div>
      <div class="span12 columns">
        <h3>Übersetzungen</h3>
          <table class="bordered-table zebra-striped">
            <tr>
              <th>Quellsprache</th>
              <th>Zielsprache</th>
              <th></th>
            </tr>

            <% @translations.each do |translation| %>
              <tr>
                <td><%= translation.source_lang %></td>
                <td><%= translation.target_lang %></td>
                <td>
                <%= link_to 'Bearbeiten', edit_translation_path(translation) %> |
                <%= link_to 'Löschen', translation, confirm: 'Are you sure?', method: :delete %></td>
              </tr>
            <% end %>
          </table>
      </div>
    </div>
  </section>
</div>

app/views/translations/new.html.erb
<div class="container">
  <div class="row">
    <div class="span16">
      <h1>Neue Übersetzung</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/translations/new.js.erb
var el = jQuery("<%= escape_javascript(render "modal_form")%>");
el.find("form").data("remote","true");
el.modal({backdrop: true});
el.modal("show");

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Source lang:</b>
  <%= @translation.source_lang %>
</p>

<p>
  <b>Target lang:</b>
  <%= @translation.target_lang %>
</p>


<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>