config/routes.rb
Zui::Application.routes.draw do

  resources :translations

  get "comments/create"

  get "comments/update"

  get "comments/destroy"

  get "comments/new"

  get "comments/edit"

  get "comments/index"

  resources :projects do
    resources :fragments do

      get "translation_mode"
      
      resources :comments do
        get "reply"
      end
    end
  end
    

  devise_for :users

  match "users" => "user#index"

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :collaborators, :through => :collaborations, :source => :user
  has_many :fragments
  has_many :comments, :through => :fragments

  attr_reader :collaborator_tokens

  def collaborator_tokens=(tokens)
    self.collaborator_ids = tokens.split(",")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @fragments = @project.fragments.order(sort_order)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @project.user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create

    @project = Project.new(params[:project])
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  private

  def sort_order
    params[:sort] || "id"
  end 

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def collaborator_list(project)
    users = project.collaborators + [project.user]
    lis = users.map{|user| content_tag(:li, user.name)}.join.html_safe
    content_tag(:ul, lis, :class => "collaborators") 
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="clearfix">
      <%= f.label :title %>
      <div class="input">
        <%= f.text_field :title, :class => "xlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :description %>
      <div class="input">
        <%= f.text_area :description, :class => "xxlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :collaborators%>
      <div class="input">
        <%= collection_select(:project, :collaborator_ids, User.where("id != ?", @project.user.id), :id, :name,{}, {:multiple => "multiple"}) %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn primary"%>
      <%= link_to 'Cancel', projects_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/projects/_list.html.erb
        <table class="zebra-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th></th>
            </tr>
          </thead>
  
          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td><%= project.title %></td>
                <td><%= truncate(project.description, :length => 200) %></td>
                <td>
                  <% if can? :read, project %>
                    <%= link_to 'Ansehen', project %>
                  <% else %>
                    Keine Berechtigung
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <section id="index">
    <div class="row">
      <div class="span4 columns">
        <h3>Aktionen</h3>
        <p>
          <%= link_to 'Neues Projekt', new_project_path, :class => "btn primary" %>
        </p>

      </div>
      <div class="span12 columns">
        <h3>Projekte</h3>
        <%= render "list" %>
      </div>
    </div>
  </section>
</div>

app/views/projects/new.html.erb
<div class="container">
  <section id="new-project">
    <div class="page-header">
      <h1>New project</h1>
    </div>
    <div class="row">
      <div class="span4 columns">
        <h3>Was macht man hier</h3>
        <p></p>

      </div>
      <div class="span12 columns">
        <%= render 'form' %>

      </div>
    </div> 
  </section>    
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>Projektübersicht</h1>
  </div>
  <div class="row">
    <div class="span4 columns">
      <h3>Text und Mitarbeiter</h3>
      <%= collaborator_list(@project) %>
        
      <% if can?(:edit, @project) %>
        <%= link_to 'Text und Mitarbeiter bearbeiten', edit_project_path(@project) %>
      <% end %>

    </div>
    <div class="span12 columns">
      <div id="project_info">
        <h3><%= @project.title %></h3>
        <p><%= @project.description %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span4 columns">
      <h3>Was man hier macht</h3>
      
      <p>
        Lorem ipsum dolor sit amet.
      </p>

    </div>
    <div class="span12 columns">
      <div id="fragments">
        <h3>Fragmente</h3>
        <% if @fragments.empty? %>
          <div class="alert-message block-message info"> 
            <p><strong>Keine Fragmente vorhanden!</strong> Um die Texte zu bearbeiten müssen sie in Fragmenten hinzugefügt werden. Fragmente können Texte oder Bilder sein.</p> 
            <div class="alert-actions"> 
              <%= link_to "Fragment erstellen", new_project_fragment_path(@project), :class => "btn small" %>
            </div> 
          </div> 
          

        <% else %>
           <table class="zebra-striped"> 
            <thead> 
            <tr> 
              <th><%= link_to "Name", :sort => "id" %></th>
              <th>Inhalt</th> 
              <th><%= link_to "Kommentare", :sort => "comments_count" %></th>
              <th><%= link_to "Letztes Update", :sort => "updated_at" %></th>
            </tr>
            </thead> 
            <tbody> 
              <% @fragments.each do |fragment| %>
                <tr>
                  <td><%= link_to fragment.title, [@project, fragment] %></td>
                  <td><%= link_to truncate(fragment.content, :length => 50), [@project, fragment] %></td>
                  <td><%= fragment.comments.count %></td>
                  <td><%= fragment.updated_at %></td>
                </tr>
              <% end %>
            </tbody> 
          </table> 
          <%= link_to "Fragment erstellen", new_project_fragment_path(@project), :class => "btn primary" %>

        <% end %>
      </div>
    </div>
  </div>
</div>