config/routes.rb
Zui::Application.routes.draw do

  resources :translations

  get "comments/create"

  get "comments/update"

  get "comments/destroy"

  get "comments/new"

  get "comments/edit"

  get "comments/index"

  resources :projects do
    resources :fragments do

      get "translation_mode"
      
      resources :comments do
        get "reply"
      end
    end
  end
    

  devise_for :users

  match "users" => "user#index"

  root :to => "home#index"

end

app/models/fragment.rb
class Fragment < ActiveRecord::Base
  belongs_to :project
  has_many :comments
  mount_uploader :image, ImageUploader
end

app/controllers/fragments_controller.rb
#encoding: utf-8
class FragmentsController < ApplicationController
  load_and_authorize_resource

  def new
    @project = Project.find(params[:project_id])
    @fragment = @project.fragments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fragment }
    end
  end

  # POST /fragments
  # POST /fragments.json
  def create
    

    @project = Project.find(params[:project_id])
    @fragment = @project.fragments.build(params[:fragment])

    respond_to do |format|
      if @fragment.save
        format.html { redirect_to @project, notice: 'Fragment was successfully created.' }
        format.json { render json: @fragment, status: :created, location: @fragment }
      else
        format.html { render action: "new" }
        format.json { render json: @fragment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @fragment = Fragment.find(params[:id])
    @project = @fragment.project
    respond_to do |f|
      f.js
    end
  end

  def update
    @fragment = Fragment.find(params[:id])

    respond_to do |format|
      if @fragment.update_attributes(params[:fragment])
        format.js { flash[:notice] = "Fragment verändert"
                    render "fragment_text"}
      end
    end
    
  end

  def translation_mode
    @fragment = Fragment.find(params[:fragment_id])
    authorize! :read, @fragment
    @comment = current_user.translation_comment(@fragment)
    @project = @fragment.project
    @origin = "translation_mode"

    respond_to do |f|
      f.html
    end
  end

  def destroy
  end

  def index
  end

  def show
    @project = Project.find(params[:project_id])
    @comments = @fragment.comments.order(:id)
    @comment = Comment.new
  end


end

app/helpers/fragment_helper.rb
module FragmentHelper
  def make_translatable(text)
    Translation.all.each do |translation|
      text.gsub!(translation.source_lang, "<span class='translated' data-translation='#{translation.target_lang}'>#{translation.source_lang}</span>")
    end
    "<div class='translatable'>#{text}</div>".html_safe
  end
end

app/views/fragments/_form.html.erb
<%= form_for([@project, @fragment], :remote => request.xhr?) do |f| %>
  <% if @fragment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fragment.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @fragment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="clearfix">
      <%= f.label :title%>
      <div class="input">
        <%= f.text_field :title, :class => "xxlarge" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :content%>
      <div class="input">
        <%= f.text_area :content, :class => "xxlarge" %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn primary"%>
        <% unless request.xhr? %>
          <%= link_to 'Cancel', @fragment.project , :class => "btn" %>
        <% end %>
    </div>
  </fieldset>
<% end %>

app/views/fragments/_fragment_text.html.erb
<h3><%= @fragment.title %></h3>
<%= Kramdown::Document.new(@fragment.content).to_html.html_safe%>
<div id="fragment_actions">
  <% if can? :edit, @fragment %>
    <%= link_to t("fragment.edit"), edit_project_fragment_path(@fragment.project, @fragment), :class => "btn", :remote => true %>
  <% end %>
    <%= link_to t("fragment.translation_mode"), project_fragment_translation_mode_path(@fragment.project, @fragment), :class => "btn" %>
</div>

app/views/fragments/create.html.erb
<h1>Fragment#create</h1>
<p>Find me in app/views/fragment/create.html.erb</p>

app/views/fragments/destroy.html.erb
<h1>Fragment#destroy</h1>
<p>Find me in app/views/fragment/destroy.html.erb</p>

app/views/fragments/edit.html.erb
<h1>Fragment#edit</h1>
<p>Find me in app/views/fragment/edit.html.erb</p>

app/views/fragments/edit.js.erb
$("#fragment_text").html("<%= escape_javascript(render "fragments/form") %>");

app/views/fragments/fragment_text.js.erb
$("#fragment_text").html("<%= escape_javascript(render("fragment_text")) %>");
$("#flash-messages").html("<%= escape_javascript(render("devise/shared/flash-messages"))%>");

app/views/fragments/index.html.erb
<h1>Fragment#index</h1>
<p>Find me in app/views/fragment/index.html.erb</p>

app/views/fragments/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Neues Fragment</h1>
  </div>
  <div class="row">
    <div class="span4 columns">
      <h3>Was macht man hier</h3>
      <p></p>

    </div>
    <div class="span12 columns">
      <%= render 'form' %>

    </div>
  </div> 
</div>

app/views/fragments/show.html.erb
<div class="container">
  <div class="row">
    <div class="span16 columns">
      <%= render "devise/shared/flash-messages" %>
      <div id="fragment_text">
        <%= render "fragment_text" %>
      </div>
      <div id="comments">
        <h3>Kommentare</h3>
        <div id="comments_text">
          <%= nested_comments @comments.arrange %>
        </div>
        <h3><%= t "comment.new" %></h3>
        <%= render "comments/form" %>
      </div>
    </div>
  </div>
</div>

app/views/fragments/translation_mode.html.erb
<ul id="selectableMenu" class="contextMenu">
  <li><span class="header">PLACEHOLDER</span></li>
  <li><a href="#google">Google</a></li>
  <li><a href="#wadoku">wadoku.eu</a></li>
  <li><a href="#edit"><span class="edit">PLACEHOLDER</span></a></li>
  <li><span class="suggestions">PLACEHOLDER</span></li>
</ul>

<div class="container">
  <div class="row">
    <div class="span16">
      <%= render "devise/shared/flash-messages" %>
    </div>
    <div id="original-wrapper" class="span6">
      <div id="original">
        <h1>Original</h1>
        <h2><%= @fragment.title %></h2>
        <%= make_translatable Kramdown::Document.new(@fragment.content).to_html.html_safe %>
      </div>
    </div>
    <div class="span10">
      <h1>Übersetzung</h1>
      <%= render "comments/form"%>
    </div>
  </div>
  <div class="row">
    <div class="span16">
      <%= link_to "Zurück zum Fragment", project_fragment_path(@project, @fragment) %>
    </div>
  </div>
</div>

app/views/fragments/update.html.erb
<h1>Fragment#update</h1>
<p>Find me in app/views/fragment/update.html.erb</p>